image: nixos/unstable
secrets:
  - 0d31234e-db98-4191-96cc-fc5cd6c4f013
  - 411a80b5-d3a1-496a-a6fe-7f9db7fa7024
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - update: |
      cd flake
      nix flake update --commit-lock-file
  - test-apollo: |
      nixos-rebuild dry-run --flake ./flake#apollo
  - test-ceres: |
      nixos-rebuild dry-run --flake ./flake#ceres --fast
  - test-diana: |
      nixos-rebuild dry-run --flake ./flake#diana --fast
  - test-minerva: |
      nixos-rebuild dry-run --flake ./flake#minerva --fast
  - test-nixos: |
      nixos-rebuild dry-run --flake ./flake#nixos --fast
  - push: |
      cd flake
      git push origin HEAD:$(git name-rev $(git rev-parse HEAD) | sed -E 's/^\S+\s(.*)$/\1/')